urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('release.views',
    # Examples:
    # url(r'^$', 'releasourcer.views.home', name='home'),
    # url(r'^releasourcer/', include('releasourcer.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^releases/$', 'index'),
    (r'^releases/(?P<release_id>\d+)/$', 'detail'),
)

urlpatterns += patterns('',
    (r'^admin/', include(admin.site.urls)),
)

release/models.py
# Releasourcer
#
# Copyright (c) 2011, Ben Selby <benmatselby@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#   * Neither the name of Ben Selby nor the names of his
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

from django.db import models
import datetime

class Release(models.Model):

    name = models.CharField('Release Name', max_length=30)
    due_date = models.DateField('Release Date')

    def __unicode__(self):
        return self.name

    def is_today(self):
        return self.due_date == datetime.date.today()
    is_today.short_description = 'Released Today?'

class Feature(models.Model):
    release = models.ForeignKey(Release)
    name = models.CharField('Feature Name', max_length=200)
    doc_link = models.TextField('Documentation Link')

    def __uniicode__(self):
        return self.name

release/views.py
# Releasourcer
#
# Copyright (c) 2011, Ben Selby <benmatselby@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#   * Neither the name of Ben Selby nor the names of his
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

from django.shortcuts import render_to_response, get_object_or_404
from release.models import Release
from datetime import datetime

def render(template, payload):
    """Render the template for relase/"""
    return render_to_response("release/"+template+".html", payload)

def index(request):
    inflight_releases = Release.objects.filter(due_date__gte=datetime.now()).order_by('due_date')
    past_releases = Release.objects.filter(due_date__lt=datetime.now()).order_by('-due_date')

    template = 'index'

    if request.GET.get('display', False) == 'wallboard':
        template = 'wallboard'

    return render(template, {
        'inflight_releases': inflight_releases,
        'past_releases': past_releases
    })

def detail(request, release_id):
    release = get_object_or_404(Release, pk=release_id)
    return render('detail', {
        'release': release
    })

templates/layout-wallboard.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <link href="/static/css/style-wallboard.css" media="screen" rel="stylesheet" type="text/css" />
    <title>{% block title %}Releasourcer{% endblock %}</title>
</head>
<body>
    <div id="wrapper">

        <div id="main">
            {% block main %}{% endblock %}
        </div>

        <div id="footer">
            Copyright &copy; {% now "Y" %} <a href="/" title="Releasourcer">Releasourcer</a>
        </div>
    </div>
</body>
</html>

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <link href="/static/css/style.css" media="screen" rel="stylesheet" type="text/css" />
    <title>{% block title %}Releasourcer{% endblock %}</title>
</head>
<body>
    <div id="wrapper">

        <div id="header">
            <a href="/releases" title="Home">Home</a> |
            <a href="" title="Past Releases">Past Releases</a> |
            <a href="/releases/?display=wallboard" title="Wallboard">Wallboard</a>

        </div>

        <div id="main">
            {% block main %}{% endblock %}
        </div>

        <div id="footer">
            Copyright &copy; {% now "Y" %} <a href="/" title="Releasourcer">Releasourcer</a>
        </div>
    </div>
</body>
</html>

templates/release/detail.html
{% extends "layout.html" %}

{% block main %}
<h1>{{ release.name }}</h1>
<p>Due Date: {{ release.due_date }}</p>
<p>Features:
{% if release.feature_set.all %}
    <ul>
        {% for f in release.feature_set.all %}
        <li>- <a href="{{ f.doc_link }}" title="{{ f.name }}">{{ f.name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    There are no features assigned to this release
{% endif %}
</p>
{% endblock %}

templates/release/index.html
{% extends "layout.html" %}

{% block main %}
<h1>Upcoming Releases</h1>
{% if inflight_releases %}

    {% for r in inflight_releases %}
    <div class="release">
        <div class="release_info">
            <a href="/releases/{{ r.id }}/" title="{{ r.name }}">{{ r.name }}</a> - {{ r.due_date }}
        </div>

        <div class="release_features">
            {% if r.feature_set.all %}
                <ul>
                    {% for f in r.feature_set.all %}
                    <li>- <a href="{{ f.doc_link }}" title="{{ f.name }}">{{ f.name }}</a></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
    {% endfor %}
{% else %}
    <p>There are no upcoming releases!</p>
{% endif %}

<div class="clear"></div>

{% endblock %}

templates/release/wallboard.html
{% extends "layout-wallboard.html" %}

{% block main %}
<h1>Upcoming Releases</h1>
{% if inflight_releases %}

    {% for r in inflight_releases %}
    <div class="release">
        <div class="release_info">
            <a href="/releases/{{ r.id }}/">{{ r.name }}</a> - {{ r.due_date }}
        </div>

        <div class="release_features">
            {% if r.feature_set.all %}
                <ul>
                    {% for f in r.feature_set.all %}
                    <li>- <a href="{{ f.doc_link }}">{{ f.name }}</a></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
    {% endfor %}
{% else %}
    <p>There are no upcoming releases!</p>
{% endif %}

<div class="clear"></div>

{% endblock %}